---
- block:
  - name: Configure iptables ports on server
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ port }}"
      jump: ACCEPT
    loop: "{{ kubernetes.firewall.inbound_server_ports }}"
    loop_control:
      loop_var: port
    when: type == 'server'

  - name: Configure iptables ports on nodes
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ port }}"
      jump: ACCEPT
    loop: "{{ kubernetes.firewall.inbound_node_ports }}"
    loop_control:
      loop_var: port
    when: type == 'node'
  become: true
