---
- block:
  - name: Configure iptables ports on masters
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ port }}"
      jump: ACCEPT
    loop: "{{ kubernetes.firewall.inbound_masters_ports }}"
    loop_control:
      loop_var: port
    when: type == 'master'

  - name: Configure iptables ports on workers
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ port }}"
      jump: ACCEPT
    loop: "{{ kubernetes.firewall.inbound_workers_ports }}"
    loop_control:
      loop_var: port
    when: type == 'worker'
  become: true
